name = "ZipStreams"
uuid = "d1ba5cbe-eaf4-46e4-b1fe-0fd0bb93243b"
authors = ["Phil Killewald <reallyasi9@users.noreply.github.com>"]
version = "2.0.0"

[deps]
CRC32 = "b4567568-9dcc-467e-9b62-c342d3a501d3"
CodecZlib = "944b1d66-785c-5afd-91f1-9de20f533193"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
StringEncodings = "69024149-9ee7-55f6-a4c4-859efe599b68"
TranscodingStreams = "3bb67fe8-82b1-5028-8e26-92a6c54297fa"

[compat]
CRC32 = "1.0"
CodecZlib = "0.7"
StringEncodings = "0.3"
TranscodingStreams = "0.9"
julia = "1.7.0"

[extras]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
LazyArtifacts = "4af54fe1-eca0-43a8-85a7-787d91b784e3"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
ZipFile = "a5390f91-8eb1-5f08-bee0-b1d1ffed6cea"

[targets]
test = ["Test", "BenchmarkTools", "LazyArtifacts", "Random", "ZipFile"]
